"""
briefing.py

Cached study briefings generated by the LLM briefing engine.
One row per generation event; most-recent is the active briefing.
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.study import Study


class Briefing(Base):
    __tablename__ = "briefings"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    study_id: Mapped[int] = mapped_column(
        ForeignKey("studies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Plain-language briefing text (markdown)
    briefing_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Which backend generated this: "openai", "anthropic", "template"
    model_used: Mapped[str] = mapped_column(String(50), nullable=False, default="template")

    # How many patterns from the library were referenced
    pattern_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    generated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    study: Mapped[Study] = relationship("Study")
